### ISSUE TITLE
`Multi-sig` feature documentation of `concordium-client`

### ISSUE THREAD

**Issue by DOBEN** [Concordium/concordium.github.io#1017]
**Task description**

Document `multi-sig` feature from this PR:
https://github.com/Concordium/concordium-client/pull/300

Add guides on how to create a multi-sig account on Concordium (two flavors):
- An account with several keys (per identity).
- An account with several identities.
The guides should consolidate the knowledge from these two guides:
https://gist.github.com/DOBEN/683fe1a7c82a0551546a7ec242d30cc0
https://gist.github.com/limemloh/8c0c55f67cf5a83ac7cc21cb646e65c1

**Sub-tasks**
- [x] Guide on how to create a multi-sig account.
- [x] Guide on how to configure `concordium-client` to have access to the keys (of a multi-sig account).
- [x] Guide/Tutorial/Example flow of a multi-sig transaction executed with `concordium-client`.
