### ISSUE TITLE
Review/update the 'Run a Node' guide

### ISSUE THREAD

**Issue by Bargsteen** [Concordium/concordium.github.io#112]
**Task description**
Review/update the 'Run a Node' guide.

**Sub-tasks**
- [ ] General review
- [ ] How to change default ports
- [ ] How to change the default gRPC token
- [ ] Which ports should and shouldn't be public

Related: #106
