### ISSUE TITLE
Add documentation for account recovery in desktop wallet.

### ISSUE THREAD

**Issue by shjortConcordium** [Concordium/concordium.github.io#249]
**Task description**

In version 1.2 of the desktop wallet, we are adding the account recovery. This means that accounts are no longer lost if the backup is (but identities still are). We need documentation for when the user should do recovery and how to do it.

[Feature proposal](https://concordium.atlassian.net/wiki/spaces/GEN/pages/809009153/Desktop+wallet+Account+Recovery)

**Sub-tasks**
- [ ] Describe how the recovery process works.
- [ ] Describe when recovery is necessary. (when the user loses their backup)
- [ ] Describe/Link to how to restore a ledger from the seed phrase.
- [ ] Describe why identities cannot be recovered.

**Comment by shjortConcordium** [comment]
Assuming that the priority is low, since the feature is not used in "normal" use cases, i.e. it is only needed if users don't make backups.
