### ISSUE TITLE
Delegation documentation

### ISSUE THREAD

**Issue by LotteKh** [Concordium/concordium.github.io#304]
Document delegation
Currently, low priority because it's scheduled for 2022.

https://concordium.atlassian.net/wiki/spaces/GEN/pages/899219463/Stake+Delegation
https://medium.com/concordium/delegating-stake-in-concordium-d4b11737905

**Sub-tasks**

- [ ] Delegation Mobile Wallet
- [ ] Delegation Desktop Wallet
- [ ] Delegation support nodes
- [ ] Conceptual topic about delegation
- [ ] Glossary terms about delegation

*Add label for component and priority.*
