### ISSUE TITLE
Document account aliases

### ISSUE THREAD

**Issue by LotteKh** [Concordium/concordium.github.io#310]
Update documentation with account alias information

**Sub-tasks**

- [ ] - Update account overview
- [ ] - Update conceptual topic about accounts
- [ ] - Add concordium-client documentation for generating aliases.

In concordium-client you can generate account aliases via
```
$ concordium-client account show-alias 3ofwYFAkgV59BsHqzmiWyRmmKRB5ZzrPfbmx5nup24cE53jNX5 --alias 17
```
This will output 
```
The requested alias for address 3ofwYFAkgV59BsHqzmiWyRmmKRB5ZzrPfbmx5nup24cE53jNX5 is 3ofwYFAkgV59BsHqzmiWyRmmKRB5ZzrPfbmx5nuou5Z2vaESRt
```

This should be added somewhere, either account overview, or mentioned in concordium-client documentation.

See [Features->Account aliases in Confluence](https://concordium.atlassian.net/wiki/spaces/GEN/pages/902070293/Account+aliases)

**Comment by concordium-cl** [comment]
@LotteKh: Note that the confluence page (with last update Oct 27) describes a different concept than what is implemented. It will be updated soon.

**Comment by dg-concordium** [comment]
@abizjak Can you comment on this please?

**Comment by abizjak** [comment]
@dg-concordium I edited the description a bit. Regarding conceptual topics, perhaps you can take this commentary https://github.com/Concordium/concordium-update-proposals/blob/main/commentary/P3-commentary.txt and revise it into something more pleasant. Let me know if that is not enough information.

**Comment by dg-concordium** [comment]
@abizjak Is this rolled out on both mainnet and testnet or only testnet?

**Comment by abizjak** [comment]
Currently only testnet. It will be on mainnet on January 17th or thereabouts.
