### ISSUE TITLE
Add documentation for enterprise identities

### ISSUE THREAD

**Issue by concordium-cl** [Concordium/concordium.github.io#340]
**Task description**
Documentation for enterprise identities must be added to *mainnet* developer documentation. Note that enterprise identities are only relevant for very few enterprises (exchanges for now) but not for the general user.

**Sub-tasks**
- [ ] find/discuss appropriate location and create new page
- [ ] review content in internal googledoc (invitation sent)
- [ ] add content from internal googledoc when finalized
- [ ] publish documentation Thursday (9-12) or Friday (10-12)
