### ISSUE TITLE
Add appropriate trademark and copyright info

### ISSUE THREAD

**Issue by dg-concordium** [Concordium/concordium.github.io#351]
Apple is the only trademark notice included, but there are other companies and products mentioned who have trademarking requirements. These need to be added. Mostly on the Downloads pages. Do we need a general copyright notice?

**Sub-tasks**
- [ ] Research uses of other trademarked products in documentation
- [ ] Add necessary markings and notices
- [ ] Research a general copyright notice that covers our use of other products.
