### ISSUE TITLE
Synchronous contract calls: Documentation

### ISSUE THREAD

**Issue by abizjak** [Concordium/concordium.github.io#384]
**Task description**

As part of the synchronous contract calls feature we will need to do a fairly extensive revision of the smart contract documentation.
https://concordium.atlassian.net/wiki/spaces/GEN/pages/914358278/Synchronous+function+calls

**Sub-tasks**
- [ ] update cargo-concordium documentation
- [ ] update relevant concordium-client documentation: `contract show` in Inspect a smart contract instance
- [ ] update documentation of contract schemas (new schema version is introduced)
- [ ] update general introduction to smart contracts, replacing the action-based interactions with call based one

Related issues
https://github.com/Concordium/concordium-node/issues/236 https://github.com/Concordium/concordium-rust-smart-contracts/issues/71 https://github.com/Concordium/concordium-wasm-smart-contracts/issues/28 https://github.com/Concordium/concordium-client/issues/108

**Comment by abizjak** [comment]
This needs to wait until the linked issues are done, or mostly done.
