### ISSUE TITLE
Updates for Sirius release on Mainnet

### ISSUE THREAD

**Issue by dg-concordium** [Concordium/concordium.github.io#474]
Updates needed for Sirius release on mainnet

**Sub-tasks**
- [ ] New branch from main once update published for testnet
- [ ] Downloads page
- [ ] Release notes
- [ ] Remove notes on delegation topics
- [ ] Remove Testnet only on SC v1 caption
- [ ] ...

*Add label for component and priority.*
