### ISSUE TITLE
Documentation updates for testnet reset

### ISSUE THREAD

**Issue by dg-concordium** [Concordium/concordium.github.io#499]
There will be documentation updates required for the testnet reset.

**Sub-tasks**
- [ ] Release notes (and what to do with the existing Testnet release notes)
- [ ] Downloads page, in particular genesis hash 
- [ ] Maybe other documentation about node migration?

**Comment by concordium-cl** [comment]
We'll need something like "everything you need to know about the testnet reset", maybe as a box on the landing page?

It must include

- short statement (why and when)
- manually delete old testnet accounts in the concordium-client folder (NOT mainnet accounts)
- stop, delete old node, then download and start new node
- ...
