### ISSUE TITLE
Guide for onboarding third party wallets

### ISSUE THREAD

**Issue by dg-concordium** [Concordium/concordium.github.io#590]
As a third party provider of a wallet I need to know how to integrate with the various endpoints to successfully create an account on the Concordium blockchain.

**Sub-tasks**
- [ ] Diagram of account flow
- [ ] Diagram of identity flow
- [ ] Diagram of recovery flow
- [ ] Step-by-step what happens in these flows, what you can do
- [ ] General description about the ID layer on Concordium
- [ ] Reference with links to existing doc (examples from repos and docs e.g. sign and submit tx etc.)

**Comment by dg-concordium** [comment]
Done for now per Emil.
