### ISSUE TITLE
ID2.0 for Android wallet

### ISSUE THREAD

**Issue by dg-concordium** [Concordium/concordium.github.io#689]
Inform users about how to use ID2.0 in the Android wallet.

**Sub-tasks**
- [ ] add to existing proofs topic
- [ ] ID cards UI changes - screenshots
- [ ] wallet connect UI changes - screenshots
