### ISSUE TITLE
Update documentation for new consensus

### ISSUE THREAD

**Issue by dg-concordium** [Concordium/concordium.github.io#750]
The documentation needs to be updated to reflect the new consensus.

**Sub-tasks**
- [ ] No finalization layer as such; references to that should be removed. Finalization occurs at block creation.
- [ ] Baker concept topic to be updated; use graphics from Christian's presentation where it makes sense.
- [ ] Delegation concept topic to be updated; use graphics from Christian's presentation where it makes sense.
- [ ] Delegation FAQ to be updated
- [ ] Adjust glossary as needed
- [ ] Adjust CCDScan documentation if updates are made to what is shown

*Add label for component and priority.*
