### ISSUE TITLE
Web3 ID documentation

### ISSUE THREAD

**Issue by dg-concordium** [Concordium/concordium.github.io#814]
Create necessary documentation and structure for Web3 ID.

**Sub-tasks**
- [ ] a section for users, explaining what these credentials are and how they can be used in wallets
- [ ] a more developer-oriented section on how to be an issuer
- [ ] a more developer-oriented section on how to be a verifier of the credentials.

https://concordium.atlassian.net/wiki/spaces/EN/pages/1128235009/Web3+ID
