### ISSUE TITLE
Move Academy into the documentation

### ISSUE THREAD

**Issue by dg-concordium** [Concordium/concordium.github.io#829]
To improve maintainability and reuse of content, move Academy into the documentation.

**Sub-tasks**
- [ ] Move content, including images
- [ ] Update brand identity https://drive.google.com/drive/folders/1EEKCFfhWo7LkSC3BQbXoRhWUgFwmBEbJ
- [ ] Set up documentation to do the build
- [ ] Publish

*Add label for component and priority.*
