### ISSUE TITLE
Developer documentation review

### ISSUE THREAD

**Issue by dg-concordium** [Concordium/concordium.github.io#854]
Small group review of documentation site and potential structural improvements for developer experience.

**Sub-tasks**
- [ ] Develop survey questions
- [ ] Kick-off meeting
- [ ] Follow-up meeting

*Add label for component and priority.*
