### ISSUE TITLE
Update sponsored transaction tutorial - test cases section

### ISSUE THREAD

**Issue by DOBEN** [Concordium/concordium.github.io#935]
**Task description**
Cis3-sponsored-transaction test cases have been significantly changed.

[https://developer.concordium.software/en/mainnet/smart-contracts/tutorials/sponsoredTransactions/sponsoredTransactionsSmartContract.html#test[…]tion](https://developer.concordium.software/en/mainnet/smart-contracts/tutorials/sponsoredTransactions/sponsoredTransactionsSmartContract.html#testing-the-signature-verification)

**Sub-tasks**
- [ ] Update the section `testing the signature verification` with up-to-date function names and screenshots
- [ ] Add section explaining how the `inside_signature` generation works in the test cases.
- [ ] Explain when to use (inside/outside signatures) e.g. `test_inside_signature_permit_transfer` vs ` test_outside_signature_permit_transfer`. Mention that `test_inside_signature_permit_transfer` should be the recommended approach.
